#pragma config(Motor,  port2,           backLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           chainbarL,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           chainbarR,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           mogo,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	motor[backLeft] = 127;
	motor[frontLeft] = 127;
	motor[backRight] = -127;
	motor[frontRight] = 127;
	wait1Msec(1800);

	motor[backLeft] = 0;
	motor[frontLeft] = 0;
	motor[backRight] = 0;
	motor[frontRight] = 0;
	motor[mogo] = -127;
	wait1Msec(250);

	motor[chainbarL] = -80;
	motor[chainbarR] = 80;
	motor[mogo] = 0;
	wait1Msec(1500);

	motor[chainbarL] = 0;
	motor[chainbarR] = 0;
	motor[claw] = -127;
	wait1Msec(500);

	motor[chainbarL] = 80;
	motor[chainbarR] = -80;
	wait1Msec(1250);

	motor[chainbarL] = 0;
	motor[chainbarR] = 0;
	motor[claw] = 0;
	motor[backLeft] = -127;
	motor[frontLeft] = -127;
	motor[backRight] = -127;
	motor[frontRight] = 127;
	wait1Msec(1125);

	motor[backLeft] = 127;
	motor[frontLeft] = 127;
	motor[backRight] = -127;
	motor[frontRight] = 127;
	wait1Msec(2000);

	playSoundFile("Yee.wav"); //sneaky memes

	motor[backLeft] = -127;
	motor[frontLeft] = -127;
	motor[backRight] = -127;
	motor[frontRight] = 127;
	wait1Msec(50);

	motor[mogo] = -127;
	wait1Msec(100);

	motor[backLeft] = 127;
	motor[frontLeft] = 127;
	motor[backRight] = -127;
	motor[frontRight] = 127;
	wait1Msec(100);

	motor[mogo] = 127;
	wait1Msec(500);

	motor[backLeft] = -127;
	motor[frontLeft] = -127;
	motor[backRight] = 127;
	motor[frontRight] = -127;
	wait1Msec(1500);

	motor[backLeft] = 0;
	motor[frontLeft] = 0;
	motor[backRight] = 0;
	motor[frontRight] = 0;
	motor[mogo] = 0;
	//right point turn
	/*motor[mogo]=50;
	wait10Msec(175);
	motor[backLeft]=motor[backRight]=motor[frontRight]=motor[frontLeft]=127;
	wait10Msec(200);
	motor[mogo]=-50;
	wait10Msec(25);
	motor[backLeft]=motor[backRight]=motor[frontRight]=motor[frontLeft]=-127;
	wait10Msec(150);
	motor[backRight]=motor[frontRight]=-127;
	motor[backLeft]=motor[frontLeft]=127;
	wait10Msec(250);
	motor[mogo]=50;
	wait10Msec(175);*/
	/*
	//left point turn
	motor[mogo]=50;
	wait10Msec(175);
	motor[backLeft]=motor[backRight]=motor[frontRight]=motor[frontLeft]=127;
	wait10Msec(200);
	motor[mogo]=-50;
	wait10Msec(25);
	motor[backLeft]=motor[backRight]=motor[frontRight]=motor[frontLeft]=-127;
	wait10Msec(150);
	motor[backRight]=motor[frontRight]=127;
	motor[backLeft]=motor[frontLeft]=-127;
	wait10Msec(250);
	motor[mogo]=50;
	wait10Msec(175);*/
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//motorname = "";
/*void slewratespositive(motorname)
{
while (motor[motorname]>0 || motor[motorname]<127)
{
motor[motorname] = motor[motorname] + 10;
wait1Msec(175);
}
if (motor[motorname]>127)
{
motor[motorname]=127;
}
}

task slewratesnegative(motorname)
{
while (motor[motorname]<0 || motor[motorname]>-127)
{
motor[motorname] = motor[motorname] - 10;
wait1Msec(175);
}
if (motor[motorname]<-127)
{
motor[motorname]=-127;
}
}*/

task usercontrol()
{
	while (true)
	{
		if (vexRT(Btn6U)==1)
		{
			while (motor[claw]>=0 || motor[claw]<=127)
			{
				motor[claw] = motor[claw] + 10;
				wait1Msec(175);
			}
			if (motor[claw]>=127)
			{
				motor[claw]=127;
			}
		}
		if (vexRT(Btn6D)==1)
		{
			while (motor[claw]<=0 || motor[claw]>=-127)
			{
				motor[claw] = motor[claw] - 10;
				wait1Msec(175);
			}
			if (motor[claw]<-127)
			{
				motor[claw]=-127;
			}
		}
		if (vexRT(Btn5U)==1)
		{
			while ((motor[chainbarL]>=0 && motor[chainbarL]<=80) || (motor[chainbarR]>=0 && motor[chainbarR]<=80))
				motor[chainbarL] = motor[chainbarL] + 10;
			{
				motor[chainbarR] = motor[chainbarR] + 10;
				wait1Msec(175);
			}
			if (motor[chainbarL]>=80 || motor[chainbarR]>=80)
			{
				motor[chainbarL]=motor[chainbarR]=80;
			}
		}
		if (vexRT(Btn5D)==1)
		{
			while ((motor[chainbarL]<=0 && motor[chainbarL]>=-80) || (motor[chainbarR]<=0 && motor[chainbarR]>=-80))
			{
				motor[chainbarL] = motor[chainbarL] - 10;
				motor[chainbarR] = motor[chainbarR] - 10;
				wait1Msec(175);
			}
			if (motor[chainbarL]<=-80 || motor[chainbarR]<=-80)
			{
				motor[chainbarL]=motor[chainbarR]=-80;
			}
		}

		if (vexRT(Btn8U)==1)
		{
			while (motor[mogo]>=0 && motor[mogo]<=127)
			{
				motor[mogo] = motor[mogo] + 10;
				wait1Msec(175);
			}
			if (motor[mogo]>=127)
			{
				motor[mogo]=127;
			}
		}
		if (vexRT(Btn8D)==1)
		{
			while (motor[mogo]<=0 || motor[mogo]>=-127)
			{
				motor[mogo] = motor[mogo] - 10;
				wait1Msec(175);
			}
			if (motor[mogo]<-127)
			{
				motor[mogo]=-127;
			}
		}

		motor[backLeft] = vexRT(Ch3);
		motor[frontLeft] = vexRT(Ch3);
		motor[backRight] = -vexRT(Ch2);
		motor[frontRight] = vexRT(Ch2);

		if(vexRT(Btn7D) == 1){
			playSoundFile("Yee.wav");
			wait1Msec(10000);
		}
		/*if (vexRT(Ch4)>0)
		{
		motor[backRight] = motor[frontRight] = 127 - vexRT(Ch4);
		motor[backLeft] = motor[frontLeft] = motor[backLeft] - motor[backRight]
		}
		if (vexRT(Ch4)<0)
		{
		motor[backLeft] = motor[frontLeft] = 127 - vexRT(Ch4) ;
		motor[backRight] = motor[frontRight] = motor[backRight] - motor[backLeft]
		}*/
	}
}
