#pragma config(Sensor, dgtl1,  elevEnc,        sensorQuadEncoder)
#pragma config(Motor,  port2,           baseL,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           baseR,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           mogo,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           elevL,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           elevR,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           cBL,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           cBR,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static int elevErr;
static int elevVal;
static int elevReq;

task elevPID(){
	elevVal = 0;
	elevReq = 0;
	while(elevReq > (elevVal + 25)){
		elevVal = SensorValue(elevEnc);
		elevErr = elevReq - elevVal;
		motor[elevL] = motor[elevR] = elevErr * 0.4;
	}
}

void auton(){
	motor[baseL] = -127;
	motor[baseR] = -127;
	wait1Msec(1500);

	motor[baseL] = 0;
	motor[baseR] = 0;
	motor[mogo] = -127;
	wait1Msec(100);

	motor[mogo] = 0;
	motor[cBL] = motor[cBR] = 127;
	wait1Msec(750);

	motor[cBL] = motor[cBR] = 0;
	motor[claw] = -127;
	wait1Msec(250);

	motor[cBL] = motor[cBR] = -127;
	wait1Msec(750);

	motor[cBL] = motor[cBR] = 0;
	motor[claw] = 0;
	motor[baseL] = 127;
	motor[baseR] = 127;
	wait1Msec(1500);

	motor[mogo] = 127;
	wait1Msec(100);

	motor[mogo] = 0;
}


task main()
{
	//startTask(elevPID);
	while(true){
		if(vexRT[Btn7D]==1){
			auton();
		}

		motor[baseL] = -vexRT[Ch3];
		motor[baseR] = -vexRT[Ch2];

		//mogo
		if(vexRT[Btn8R]==1){
			motor[mogo] = 127;
		}
		else if(vexRT[Btn8U]==1){
			motor[mogo] = -127;
		}
		else{
			motor[mogo] = 0;
		}

		//chainbar
		if(vexRT[Btn6U]==1){
			motor[cBL] = motor[cBR] = -127;
		}
		else if(vexRT[Btn6D]==1){
			motor[cBL] = motor[cBR] = 127;
		}
		else{
			motor[cBL] = motor[cBR] = 0;
		}

		//elevator
		if(vexRT[Btn7U]==1){
			motor[elevL] = motor[elevR] = 127;
		}
		else if(vexRT[Btn7L]==1){
			motor[elevL] = motor[elevR] = -127;
		}
		else{
			motor[elevL] = motor[elevR] = 0;
		}

		//claw
		if(vexRT[Btn5U]==1){
			motor[claw] = -127;
		}
		else if(vexRT[Btn5D]==1){
			motor[claw] = 127;
		}
		else{
			motor[claw] = 0;
		}
	}
}
