#pragma config(Sensor, dgtl1,  baseEnc,        sensorQuadEncoder)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

//speaker meme task
task speakMeDaddy(){
	while(true){
		//Yee.wav on 7D
		if(vexRT(Btn7D) == 1){
			playSoundFile("Yee.wav");
			wait1Msec(10000);
		}
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	motor[backLeft] = 127;
	motor[frontLeft] = 127;
	motor[backRight] = -127;
	motor[frontRight] = 127;
	wait1Msec(1800);

	motor[backLeft] = 0;
	motor[frontLeft] = 0;
	motor[backRight] = 0;
	motor[frontRight] = 0;
	motor[mogo] = -127;
	wait1Msec(250);

	motor[liftL] = -80;
	motor[liftR] = 80;
	motor[mogo] = 0;
	wait1Msec(1500);

	motor[liftL] = 0;
	motor[liftR] = 0;
	motor[claw] = -127;
	wait1Msec(500);

	motor[liftL] = 80;
	motor[liftR] = -80;
	wait1Msec(1250);

	motor[liftL] = 0;
	motor[liftR] = 0;
	motor[claw] = 0;
	motor[backLeft] = -127;
	motor[frontLeft] = -127;
	motor[backRight] = -127;
	motor[frontRight] = 127;
	wait1Msec(1000);

	motor[backLeft] = 127;
	motor[frontLeft] = 127;
	motor[backRight] = -127;
	motor[frontRight] = 127;
	wait1Msec(2000);

	playSoundFile("Yee.wav"); //sneaky memes

	motor[backLeft] = -127;
	motor[frontLeft] = -127;
	motor[backRight] = -127;
	motor[frontRight] = 127;
	wait1Msec(50);

	motor[mogo] = -127;
	wait1Msec(100);

	motor[backLeft] = 127;
	motor[frontLeft] = 127;
	motor[backRight] = -127;
	motor[frontRight] = 127;
	wait1Msec(100);

	motor[mogo] = 127;
	wait1Msec(500);

	motor[backLeft] = -127;
	motor[frontLeft] = -127;
	motor[backRight] = 127;
	motor[frontRight] = -127;
	wait1Msec(1500);

	motor[backLeft] = 0;
	motor[frontLeft] = 0;
	motor[backRight] = 0;
	motor[frontRight] = 0;
	motor[mogo] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		//speaker memes
		startTask(speakMeDaddy);

		while(1==1){

			//driving
			motor[backLeft] = -vexRT(Ch3);
			motor[frontLeft] = -vexRT(Ch3);
			motor[backRight] = vexRT(Ch2);
			motor[frontRight] = -vexRT(Ch2);

			//lift down
			if(vexRT(Btn6U) == 1){
				motor[liftL] = 127;
				motor[liftR] = -127;
			}
			//lift up
			else if(vexRT(Btn6D) == 1){
				motor[liftL] = -127;
				motor[liftR] = 127;
			}
			//lift stopped
			else {
				motor[liftL] = 0;
				motor[liftR] = 0;
			}

			//claw open (closes by banding if motor not being used)
			if(vexRT(Btn5D) == 1){
				motor[claw] = -127;
			}

			//claw stopped
			else{
				motor[claw] = 0;
			}

			//mogo down
			if(vexRT(Btn8U) == 1){
				motor[mogo] = -127;
			}
			//mogo up
			else if(vexRT(Btn8R) == 1){
				motor[mogo] = 127;
			}
			//mogo stopped
			else{
				motor[mogo] = 0;
			}
		}
	}
}
