#pragma config(Sensor, in1,    mogopot,        sensorPotentiometer)
#pragma config(Sensor, dgtl2,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  rightEnc,       sensorQuadEncoder)
#pragma config(Motor,  port2,           mogomotor,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorNone, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorNone, openLoop)
#pragma config(Motor,  port5,           frontLeft,     tmotorNone, openLoop)
#pragma config(Motor,  port6,           backLeft,      tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	if (vexRT(Btn5D) == 1)
	{
		motor[mogomotor] = 127;
		if (SensorValue(mogopot) >= 3500)
		{
			motor[mogomotor] = 0;
		}
		motor[frontRight] = 127;
		motor[backRight] = 127;
		motor[frontLeft] = 127;
		motor[backLeft] = 127;
		wait1Msec(3000);
		motor[mogomotor] = -127;
		if (SensorValue(mogopot) <= 0)
		{
			motor[mogomotor] = 0;
		}
	}
	*/

	if (vexRT(Btn5U)==1)
	{
		motor[mogomotor] = 127;
	}
	else
	{
		motor[mogomotor] = 0;
	}
}
