#pragma config(Sensor, dgtl1,  solenoid,       sensorDigitalOut)
#pragma config(Motor,  port2,           WheelL1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           WheelL2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ripper,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           WheelR2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           WheelR1,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)*/
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*float Kp = 0.01;
int setpoint = 0;
int processvariable = 0;
float error = 0;*/

/*task pidController()
{
while(true)
{
processvariable = SensorValue(potentiometer);
error = setpoint - processvariable;
motor[ripper] = error * Kp;
wait1Msec(5);
}
}*/

task main()
{
	//startTask(pidController);
	/*while(1==1)
	{
	if(vexRT[Btn5U] == 1)
	{
	setpoint = setpoint + 10;
	}

	if(vexRT[Btn5D] == 1)
	{
	setpoint = setpoint - 10;
	}

	if(setpoint < 0)
	{
	setpoint = 0;
	}

	else if(setpoint > 4095)
	{
	setpoint = 4095;
	}
	wait1Msec(10);
	}*/
	short Deadzone=20;
	while (true)
	{
		//drive motors (left and right)
		if(abs(vexRT[Ch3]) >= Deadzone)
		{
			motor[WheelL1] = motor[WheelL2] = vexRT[Ch3];
		}
		else
		{
			motor[WheelL1]=motor[WheelL2] = 0;
		}
		if(abs(vexRT[Ch2]) >= Deadzone)
		{
			motor[WheelR1]=motor[WheelR2] = vexRT[Ch2];
		}
		else
		{
			motor[WheelR1]=motor[WheelR2]= 0;
		}
		if(vexRT[Btn5U]==1)
		{
			motor[ripper] = 4095;
		}
		if(vexRT[Btn5D]==1)
		{
			motor[ripper] = -4095;
		}
		else
		{
			motor[ripper] = 0;
		}
	}
}
