#pragma config(Motor,  port1,           leftbotdrive,  tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           rightrightarm, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftleftarm,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftrightarm,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightleftarm,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lefttopdrive,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           righttopdrive, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           koji,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           flipper,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightbotdrive, tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma autonomousDuration(20)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{

	bStopTasksBetweenModes = false;
	bDisplayCompetitionStatusOnLcd = false;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*------- --------------------------------------------------------------------*/

task autonomous()
{
	while (true)
	{
		motor[leftbotdrive] = 127;
		motor[lefttopdrive] = 127;
		motor[rightbotdrive] = 127;
		motor[righttopdrive] = 127;
		wait1Msec(500);
		motor[leftbotdrive] = -127;
		motor[lefttopdrive] = -127;
		motor[rightbotdrive] = 127;
		motor[righttopdrive] = 127;
		wait1Msec(500);
	}
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	// AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	short Deadzone=20;
	while (true)
	{
		//drive motors (left and right)
		if(abs(vexRT[Ch3]) >= Deadzone)
		{
			motor[lefttopdrive] = vexRT[Ch3];
			motor[leftbotdrive] = vexRT[Ch3];
		}
		else
		{
			motor[lefttopdrive] = 0;
			motor[leftbotdrive] = 0;
		}
		if(abs(vexRT[Ch2]) >= Deadzone)
		{
			motor[righttopdrive] = vexRT[Ch2];
			motor[rightbotdrive] = vexRT[Ch2];
		}
		else
		{
			motor[righttopdrive]= 0;
			motor[rightbotdrive] = 0;
		}

		//arm control
		if((vexRT[Btn6U]) == 1)
		{
			motor[leftleftarm]=127;
			motor[leftrightarm]=127;
			motor[rightrightarm]=127;
			motor[rightleftarm]=127;
		}
		else if((vexRT[Btn6D]) == 1)
		{
			motor[leftleftarm]=-127;
			motor[leftrightarm]=-127;
			motor[rightrightarm]=-127;
			motor[rightleftarm]=-127;
		}

		else
		{
			motor[leftleftarm]=0;
			motor[leftrightarm]=0;
			motor[rightrightarm]=0;
			motor[rightleftarm]=0;
		}


		//flipper control
		if ((vexRT[Btn5U]) == 1)
		{
			motor[flipper]=127;
		}
		else if ((vexRT[Btn5D]) == 1)
		{
			motor[flipper]=-127;
		}
		else
		{
			motor[flipper]=0.2 * 127;
		}
		//servoTest
		if ((vexRT[Btn8U]) == 1)
		{
			motor[koji]=127;
		}
		else if ((vexRT[Btn8D]) == 1)
		{
			motor[koji]=-127;
		}
		else
		{
			motor[koji]=0;
		}
	}
}
// This is the main execution loop for the user control program.
// Each time through the loop your program should update motor + servo
// values based on feedback from the joysticks.

// ........................................................................
// Insert user code here. This is where you use the joystick values to
// update your motors, etc.
// ........................................................................

// Remove this function call once you have "real" code.
