#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/** **/


task speakMeDaddy(){
	while(true){
		if(vexRT(Btn7D) == 1){
			playSoundFile("Yee.wav");
			wait1Msec(10000);

		}
	}
}


task main()
{

startTask(speakMeDaddy);
while(1==1){

	motor[backLeft] = -vexRT(Ch3);
	motor[frontLeft] = -vexRT(Ch3);
	motor[backRight] = vexRT(Ch2);
	motor[frontRight] = -vexRT(Ch2);
	if(vexRT(Btn6U) == 1){
		motor[liftL] = 100;
		motor[liftR] = -100;
	}
	else if(vexRT(Btn6D) == 1){
		motor[liftL] = -100;
		motor[liftR] = 100;
	}
	else {
		motor[liftL] = 0;
		motor[liftR] = 0;
	}
	if(vexRT(Btn5U) == 1){
		motor[claw] = 127;
	}
	else if(vexRT(Btn5D) == 1){
		motor[claw] = -127;
	}
	else{
		motor[claw] = 0;
	}
	if(vexRT(Btn8U) == 1){
		motor[mogo] = 127;
	}
	else if(vexRT(Btn8R) == 1){
		motor[mogo] = -127;
	}
	else{
		motor[mogo] = 0;
	}
}


}
